sudo: false
language: php
php:
 - "5.5"
 - "5.6"
 - "7.0"
 - "hhvm"

before_install:
 - composer self-update
 - composer install --dev --prefer-source

script:
 - ./vendor/bin/php-cs-fixer --version
 - ./vendor/bin/php-cs-fixer fix -v --dry-run
 - phpunit
