sudo: false
language: php

matrix:
  fast_finish: true
  include:
  - php: 5.5
  - php: 5.6
  - php: 7
  - php: hhvm
  allow_failures:
  - php: hhvm

before_install:
 - phpenv config-rm xdebug.ini
 - travis_retry composer self-update

install:
 - travis_retry composer install --dev --no-interaction

script:
 - ./vendor/bin/php-cs-fixer --version
 - ./vendor/bin/php-cs-fixer fix -v --dry-run
 - ./vendor/bin/phpunit

cache:
 directories:
 - $HOME/.composer/cache
 - vendor
